language: node_js
node_js:
  - "10"
install:
  - npm install gulp -g
  - npm install
script:
  - gulp
after_script:
  - cd ./build
  - git init
  - git config user.name "AlanDecode"
  - git config user.email "zytbuaa1415@gmail.com"
  - git add .
  - git commit -m "Travis build"
  - git push --force --quiet "https://${travisexsearch}@${GH_REF}" master:master
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/AlanDecode/Typecho-Plugin-ExSearch.git