name: Build

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Build
      run: |
        npm install
        gulp
    - name: Deploy Build
      uses: docker://peaceiris/gh-pages:v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./build
      with:
        emptyCommits: false
